name: Build and Test

on:
  push:
    branches:
      - 'develop'
      - 'release-*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run-script build:ci
      - name: Test
        run: npm run-script test:ci

